baseURL = 'https://hugo.8888-8888.me/'
languageCode = 'zh-Hans'
title = '你也不是我的救赎'
theme = 'PaperMod'

[module]
  [[module.imports]]
    path = "github.com/hugomods/encrypt"
  [[module.imports]]
    path = "github.com/hugomods/pwa"

enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = true
buildDrafts = false
buildFuture = true
buildExpired = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  # env = "production"
  title = "你也不是我的救赎"
  description = "蔡的小破站 - 记录技术学习与生活感悟，分享编程智慧"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "cai6"
  # images = ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat = "2006-01-02"
  hideFooter = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  [params.assets]
    favicon = "img/personal/avatar.png"
    favicon16x16 = "img/personal/avatar.png"
    favicon32x32 = "img/personal/avatar.png"
    apple_touch_icon = "img/personal/avatar.png"
    safari_pinned_tab = "img/personal/avatar.png"

  [params.label]
    text = "你也不是我的救赎"
    icon = "img/personal/avatar.png"
    iconHeight = 35

  [params.profileMode]
    enabled = false
    title = "你也不是我的救赎"
    subtitle = "蔡的小破站 - 记录技术学习与生活感悟，分享编程智慧"
    imageUrl = "img/personal/avatar.png"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "cai6"
    buttons = [
      { name = "Posts", url = "posts" },
      { name = "Tags", url = "tags" },
      { name = "Github", url = "https://github.com/pengcai6" }
    ]

  [params.socialIcons]
    Github = "https://github.com/pengcai6"

  [params.encrypt]
    password = "cai6blog2025"
    storage = "session"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags"
    weight = 40
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about"
    weight = 50
  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search"
    weight = 60
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives"
    weight = 70

[services]
  [services.googleAnalytics]
    ID = 'G-N5X29L48P4'

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
